[CITE-104] Migration to Thymeleaf
diging/citesphere pull request #123
Opened 2020-11-23 20:40 UTC by radhikanyati94

2020-11-24 21:45 UTC, jdamerow requested changes
Please resolve codefactor warnings.

2020-11-24 21:45 UTC, jdamerow commented
Make it so, Jenkins.

2020-11-24 22:05 UTC, jdamerow commented
- the footer should be fixed at the bottom as before
- forward and backward icons are not shown
![image](https://user-images.githubusercontent.com/8881141/100155859-fb791580-2e75-11eb-80dc-a30268e27e87.png)
- clicking on next page produces an error page, not sure what's going on there, the page only seems to work when I click on a group from the home page; no exceptions in log; this only happens in the dev-test group though for some reason
- the URL connector when editing a contributor (author, editor, etc) does not work
- saving throws a null pointer

2020-12-14 19:17 UTC, radhikanyati94 commented
I updated the footer position to relative because it was overriding the table on items page. I will check for some other fix.

2020-12-15 18:00 UTC, jdamerow commented
Make it so, Jenkins.

2020-12-15 18:07 UTC, jdamerow commented
Make it so, Jenkins.

2020-12-15 18:13 UTC, jdamerow commented
Make it so, Jenkins.

2020-12-15 18:50 UTC, jdamerow commented
Make it so, Jenkins.

2021-01-05 15:26 UTC, jdamerow commented
Make it so, Jenkins.

2021-01-05 15:58 UTC, jdamerow requested changes
Just remove those commented out lines and it should be good to go

2021-01-05 15:58 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/concepts/list.html
> + 		<!-- <td th:text="${concept.uri}"></td>  -->
remove if not needed

2021-01-05 15:58 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/concepts/types/list.html
> + 		<!-- <td th:text="${concept.uri}"></td>  -->
remove

2021-01-07 19:21 UTC, merged