[CITE-134] Add group to Authority Entry
diging/citesphere pull request #144
Opened 2021-03-18 22:38 UTC by radhikanyati94

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
The group should be a citation group. Every user that has access to a group should be able to add/edit/delete authorities from that group. When a new authority is created a user should choose if that authority would be part of the citation group it is being created for (default) or just available to the user (no group).

An authority can belong to more than one group.

The "Manage Authority Entries" page should show the authorities categorized by group. E.g. a user would select a group and then see all authorities in that group.
https://diging.atlassian.net/browse/CITE-134
  
## Anything else the reviewer needs to know?

This PR can be merged only after the following PR is merged: https://github.com/diging/citesphere-model/pull/12

2021-03-22 16:33 UTC, jdamerow requested changes
- pom changes are missing
- and also, I released the model plugin, so you can use the release version now (it sometimes takes a while though till eclipse finds it in maven central).

2021-03-22 16:33 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityEntryController.java
> +                    authorityEntry.get().setGroups(authorityGroups);
if `authorityGroups` is already initialized this line doesn't really do anything. In your if statement I would check `authorityEntry.get().getGroups() == null` and if so, initialize the list. Then just add the new group id. Also, make sure there are no duplicates in the list.

2021-03-23 17:05 UTC, jdamerow requested changes

2021-03-23 17:05 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/group/editItem.html
> +			createManageAuthorityURL = [[@{|/auth/authority/add?${_csrf.parameterName}=${_csrf.token}|}]]+ '&source=conceptpower&uri=' + uri;
since it's changing this line anyways, let's send the csrf token via the body.

2021-03-23 17:06 UTC, jdamerow commented
Make it so, Jenkins.

2021-03-23 17:17 UTC, jdamerow commented
- the drop down on the manage authority page should use bootstrap classes
- let's put the checkbox to add an authority to the group above the results or it's not noticeable (especially if there are many results).
- let's add a column that shows the groups an authority belongs to on the authority list page

2021-03-30 13:58 UTC, jdamerow commented
Make it so, Jenkins.

2021-03-30 14:10 UTC, jdamerow requested changes
on the authority list page, there needs to be an option to see all authorities that are not in a group.

2021-03-30 14:10 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/group/editItem.html
> +							<input type="checkbox" id="mycheckbox" name="mycheckbox" th:checked="checked"> Add Authority to the Group
Let's say "Add authority to group [group name]".

2021-03-30 18:59 UTC, radhikanyati94 commented
Converted this pull request to draft because it can be merged only after https://github.com/diging/citesphere-model/pull/14 is merged. The build is failing because the model version mentioned in pom.xml doesn't exist.

2021-04-08 14:58 UTC, jdamerow requested changes

2021-04-08 14:58 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/AuthorityService.java
> +    public String getGroupNameByGroupId(String citationGroupId) throws GroupDoesNotExistException {
the group manager has a get group method, doesn't it? why don't you use that one?

2021-04-08 16:09 UTC, radhikanyati94 commented on citesphere/pom.xml
> +        <citesphere.model.version>1.8</citesphere.model.version>
Yes, but I have an open pull request in citesphere-model https://github.com/diging/citesphere-model/pull/14/files. Once it is merged, the version will be 1.8.

2021-04-08 17:05 UTC, jdamerow commented
Ha, I thought I checked that but I guess I missed it 😳

---
Julia Damerow, PhD
Scientific Software Engineer
Global Biosocial Complexity Initiative
Digital Innovation Group
Arizona State University
email: ***@***.*** <>
web: http://diging.asu.edu, https://complexity.asu.edu/















> On Apr 8, 2021, at 12:09 PM, radhikanyati94 ***@***.***> wrote:
> 
> 
> @radhikanyati94 commented on this pull request.
> 
> In citesphere/pom.xml <https://github.com/diging/citesphere/pull/144#discussion_r609863897>:
> 
> > @@ -25,7 +25,7 @@
>          <spring.kafka.version>2.2.6.RELEASE</spring.kafka.version>
>          <spring-social-zotero.version>0.7</spring-social-zotero.version>
>          <citesphere.messages.version>0.4</citesphere.messages.version>
> -        <citesphere.model.version>1.5</citesphere.model.version>
> +        <citesphere.model.version>1.8</citesphere.model.version>
> Yes, but I have an open pull request in citesphere-model https://github.com/diging/citesphere-model/pull/14/files <https://github.com/diging/citesphere-model/pull/14/files>. Once it is merged, the version will be 1.8.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub <https://github.com/diging/citesphere/pull/144#discussion_r609863897>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACDYH5MZGMCAZQDWQCASTGLTHXIM3ANCNFSM4ZNR53QA>.
>

2021-04-16 14:38 UTC, jdamerow commented
Make it so, Jenkins.

2021-04-16 14:51 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/authorities/list.html
>  	<td><a th:href="@{${authority.id}+'/edit'}"><i class="far fa-edit" title="Edit"></i></a></td>
This link doesn't work anymore now because it is relative and creates the wrong link when a group or the user has been selected.

2021-04-16 14:52 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/authorities/list.html
>  	<td><a th:href="@{${authority.id}+'/edit'}"><i class="far fa-edit" title="Edit"></i></a></td>
And neither does the delete link.

2021-04-19 21:18 UTC, jdamerow commented
Make it so, Jenkins.

2021-04-19 21:28 UTC, merged