Story/cite 147
diging/citesphere pull request #161
Opened 2021-06-22 22:13 UTC by MaulikLim

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[CITE-147] - Attachments need to be shown on citation page  
## Anything else the reviewer needs to know?

I have removed unused imports from MongoTemplate class.

2021-07-08 20:19 UTC, jdamerow commented
please update citesphere-model version and reopen.

2021-07-15 16:28 UTC, jdamerow requested changes
and then reopen when the module prs have been merged and this can be deployed.

2021-07-20 13:13 UTC, jdamerow commented
> and then reopen when the module prs have been merged and this can be deployed.

Are the module PRs merged? If so, the versions are not updated and this is still draft PR. Is there a reason for that?

2021-07-20 16:29 UTC, MaulikLim commented
The module PRs have been merged. I believe the spring-social-zotero 0.9 and citsphere.model 1.10 does not contain the new code and so I am using the current snapshots from develop for these modules. I also tested it on my machine. Do I need to change anything else? I kept it as draft PR as I thought it has not yet been reviewed due to module version mismatch.

2021-07-20 17:51 UTC, jdamerow commented
I looked it over but need to see it deployed. So just reopen when the other plugins have been released and the above change has been made.

2021-07-20 17:53 UTC, jdamerow commented
Also, which pull request is this one waiting for? for spring-social-zotero there only seem to be a PR for 148 and there is none for citesphere-model.

2021-07-20 17:53 UTC, MaulikLim commented
Module PRs have already been merged

2021-07-20 17:54 UTC, MaulikLim commented
Okay, I'll reopen after the plugin releases are done.

2021-07-20 17:56 UTC, jdamerow commented
citesphere-model has already been released I believe. I'll release spring-social-zotero now.

2021-07-20 18:00 UTC, MaulikLim commented
This was merged after the citesphere-model 1.10 release

2021-07-20 18:01 UTC, jdamerow commented
there is a 1.11 release
https://github.com/diging/citesphere-model/releases/tag/1.11-4-g8d4b95a

2021-07-20 18:11 UTC, MaulikLim commented
It was merged after 1.11 too.

2021-07-20 18:13 UTC, jdamerow commented
ah right, the pull request didn't show up first in the list. I'll release it now.

2021-07-20 18:35 UTC, MaulikLim commented
Updated the plugin versions.

2021-07-23 20:51 UTC, jdamerow requested changes

2021-07-23 20:51 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +                if (!group.getUsers().contains(user.getUsername())) {
is there a reason for this duplicate if statement?

2021-07-23 20:51 UTC, jdamerow commented
Make it so, Jenkins.

2021-07-23 21:09 UTC, jdamerow commented
Beside that, it should be good to go (although there seems to be an issue with the syncing but I'll check that later and will write a separate ticket if necessary).

2021-07-23 21:23 UTC, jdamerow commented
Oh and one thing, for the attachment list, let's use an attachment icon instead of a bullet point.

2021-07-23 22:07 UTC, MaulikLim commented
Used attachment icon and removed the duplicate if condition

2021-07-26 19:58 UTC, jdamerow commented
Make it so, Jenkins.

2021-07-26 21:10 UTC, merged