Story/cite 93 - citations page should update while sync is running
diging/citesphere pull request #173
Opened 2021-09-07 23:36 UTC by NarmadaRavali

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

...Put description here...

citations page should update while sync is running
  
## Anything else the reviewer needs to know?

... describe here ...

2021-09-13 18:23 UTC, MaulikLim approved these changes

2021-09-13 18:43 UTC, Charishma0249 approved these changes

2021-09-17 14:42 UTC, jdamerow requested changes
It looks like the page is built in two separate controllers now. Once in the controller that backs the page and once on poll. This means if something changes, it has to be changed in two places and currently it looks like there is probably a lot of duplicate code as the page backing controller doesn't seem to have been changed? It should be enough to not transfer any items data from the page backing controller and always load the items information asynchronically even there were no changes.

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/CitationsDto.java
> +    CitationsDto(ICitation citation, String label, String icon) {
is there a reason this constructor is not public?

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/CitationsDto.java
> +public class CitationsDto {
needs javadoc

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/ItemsDataDto.java
> +public class ItemsDataDto {
needs javadoc

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/UpdateItemsPageController.java
> +            return null;
You want to make sure a 404 is returned in this case. This will probably return a 500.

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/UpdateItemsPageController.java
> +            return null;
see above

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/UpdateItemsPageController.java
> +public class UpdateItemsPageController {
why is this class called "UpdateItems..."? it doesn't seem to update anything.

2021-09-17 14:42 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/group/items.html
> +		'</tr>')
the header row doesn't change, does it? So it wouldn't need to be added every time.

2021-09-20 16:49 UTC, NarmadaRavali commented
> It looks like the page is built in two separate controllers now. Once in the controller that backs the page and once on poll. This means if something changes, it has to be changed in two places and currently it looks like there is probably a lot of duplicate code as the page backing controller doesn't seem to have been changed? It should be enough to not transfer any items data from the page backing controller and always load the items information asynchronically even there were no changes.

Yeah I agree, there is a lot of duplicate code. That means, I have to make the main controller load items data asynchronically and remove the other controller. Am I right?

2021-09-20 16:53 UTC, jdamerow commented
I think you can just remove the items code from the controller that backs the page and then make sure the other controller is called at least once when the page loads (from js).

2021-09-20 16:56 UTC, NarmadaRavali commented
> I think you can just remove the items code from the controller that backs the page and then make sure the other controller is called at least once when the page loads (from js).

 That means I should be removing html code that uses modal data to create the page and rewrite the page only in javascript right?

2021-09-20 16:57 UTC, jdamerow commented
Yes, but I don't think you need to rewrite that much, since you already have the code to insert items into the page.

2021-09-20 16:59 UTC, NarmadaRavali commented
> Yes, but I don't think you need to rewrite that much, since you already have the code to insert items into the page.

Yes, that's true. I already wrote all the page elements. Might need some additions before I remove all HTML code.

2021-11-05 20:10 UTC, tjquinn1 commented
Fix code factor issues

2022-01-05 18:01 UTC, jdamerow commented
Make it so, Jenkins.

2022-01-05 18:14 UTC, jdamerow commented
- pagination doesn't work anymore
- there should be a spinner at the end of the table to indicate when the table is still being loaded
- there is a a lot of white space after the table
- the new entries don't seem to be added at the end of the table or something. when you search (e.g. search for 'a' in the dev-test group), you can see how the second row of the table keeps changing

2022-01-05 18:14 UTC, closed without merging