Story/cite 41
diging/citesphere pull request #184
Opened 2021-10-22 19:46 UTC by MaulikLim

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[CITE-41] - It should be possible to filter citations by concepts.
  
## Anything else the reviewer needs to know?

previous branch - https://github.com/diging/citesphere/tree/story/CITE-41

[CITE-41]: https://diging.atlassian.net/browse/CITE-41?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-01-11 21:02 UTC, jdamerow requested changes

2022-01-11 21:02 UTC, jdamerow commented on citesphere/pom.xml
> +        <citesphere.model.version>1.13</citesphere.model.version>
I believe this needs to be 1.14?

2022-01-20 17:35 UTC, MaulikLim commented on citesphere/pom.xml
> +        <citesphere.model.version>1.13</citesphere.model.version>
This has been fixed now

2022-02-04 14:50 UTC, jdamerow commented
Resolve conflicts please

2022-02-22 17:24 UTC, jdamerow commented
Make it so, Jenkins.

2022-02-22 17:26 UTC, jdamerow commented
There are compilation errors:
```
[ERROR] /var/lib/jenkins/workspace/citesphere_deploy_to_review_on_pr/citesphere/src/test/java/edu/asu/diging/citesphere/core/export/impl/ExportManagerTest.java:[88,37] method getGroupItems in interface edu.asu.diging.citesphere.core.service.ICitationManager cannot be applied to given types;
  required: edu.asu.diging.citesphere.user.IUser,java.lang.String,java.lang.String,int,java.lang.String,java.util.List<java.lang.String>
  found: edu.asu.diging.citesphere.user.IUser,java.lang.String,<nulltype>,int,java.lang.String
  reason: actual and formal argument lists differ in length
```

2022-02-22 18:20 UTC, MaulikLim commented
Fixed test cases

2022-02-22 18:59 UTC, jdamerow commented
- let's make the concepts checkboxes, so it's obvious they can be checked/unchecked
- there should be a select/deselect all button
- there should be a filter to search within the concept
- not sure what currently happens if the list gets very long, but there should be a scrollbar (it shouldn't just keep going).
- the dropdown menu should say "Filter by Concept"

2022-03-17 17:27 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-24 18:45 UTC, jdamerow commented
Make it so, Jenkins.

2022-03-24 18:50 UTC, merged