Story/cite 91
diging/citesphere pull request #190
Opened 2021-11-17 17:33 UTC by MaulikLim

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[CITE-91] - It should be possible to revert a citation to a previous version
[CITE-90] - It should be possible to see previous versions of a citation
  
## Anything else the reviewer needs to know?

Combined pull request for 2 tickets

2022-01-14 15:01 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/RevertCitationController.java
> +            logger.error(e.getMessage());
log complete stack trace

2022-01-14 15:02 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/RevertCitationController.java
> +    ICitationVersionManager citationVersionManager;
should be private

2022-02-07 17:26 UTC, jdamerow requested changes

2022-02-07 17:26 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationVersionManager.java
> +            throw new GroupDoesNotExistException("Group with id " + groupId + " does not exist.");
`ex` should be passed into the new exception to keep a valid stack trace

2022-02-07 17:26 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationVersionManager.java
> +            throw new GroupDoesNotExistException("Group with id " + groupId + " does not exist.");
see above

2022-02-07 17:27 UTC, jdamerow commented
Make it so, Jenkins.

2022-02-07 17:36 UTC, jdamerow commented
The original version never seems to be stored. The version that is first stored is the one after it has been changed. Also, the version page that lists all versions should also include the time of a version (not just the date)

2022-02-22 17:32 UTC, jdamerow commented
Make it so, Jenkins.

2022-02-22 17:44 UTC, jdamerow commented
- the updated by column always contains "unauthenticated"
- the files portion of the items page (for a previous version) is empty

2022-02-22 21:55 UTC, MaulikLim commented
![image](https://user-images.githubusercontent.com/25862427/155225619-a46fcf71-7479-44f9-935a-79b3715c4d29.png)


> * the updated by column always contains "unauthenticated"
> * the files portion of the items page (for a previous version) is empty

- It shows "unauthenticated" when the item is updated through sync. The author of the generated history is provided by Spring security. For me, it shows my username when I edit the item.
- Fixed the files portion.

2022-02-22 21:58 UTC, jdamerow commented
Then let's make it "Sync Process" instead of "unauthenticated"

2022-02-22 22:17 UTC, MaulikLim commented
> Then let's make it "Sync Process" instead of "unauthenticated"

Done

2022-03-18 13:20 UTC, jdamerow requested changes

2022-03-30 18:23 UTC, jdamerow commented
Make it so, Jenkins.

2022-04-01 15:52 UTC, jdamerow commented
Make it so, Jenkins.

2022-04-01 15:56 UTC, merged