Story/cite 186
diging/citesphere pull request #222
Opened 2023-02-03 22:25 UTC by agoyal61

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
 

https://diging.atlassian.net/browse/CITE-186

... Put ticket description here and add link to ticket ...

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2023-03-02 22:37 UTC, jdamerow requested changes

2023-03-02 22:37 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityListController.java
> +            logger.warn("Trying to access invalid page number: " + page);
same as above

2023-03-02 22:37 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/authorities/list.html
> +     	    	 console.log("all")
remove

2023-03-02 22:37 UTC, jdamerow commented on citesphere/src/main/webapp/WEB-INF/views/auth/authorities/list.html
> +    	    }
this looks like the same code as below in the `$("#displayAuthorities").change` function. Should be DRY.

2023-03-02 22:37 UTC, jdamerow commented on citesphere/src/test/java/edu/asu/diging/citesphere/core/service/impl/AuthorityServiceTest.java
> +    public void test_getUserSpecificAuthorities() {
same as above

2023-03-16 17:37 UTC, jdamerow requested changes

2023-03-16 17:37 UTC, jdamerow commented on citesphere/src/test/java/edu/asu/diging/citesphere/core/service/impl/AuthorityServiceTest.java
> +            Assert.assertTrue(!entry.getName().contains("Einstein"));
what are these asserts testing? the point is that all entries returned by the entryRepository are also returned by the manager, not that the names include "Albert" but not "Einstein".

2023-03-16 18:16 UTC, jdamerow commented
Make it so, Jenkins.

2023-03-21 15:55 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityListController.java
> +        pageInt = (pageInt - 1) < 0 ? 0 : pageInt - 1;
see above

2023-03-22 17:47 UTC, jdamerow commented
When I go to a group that doesn't have any entries, i get this error (and the drop down is broken afterwards):
```
jquery.twbsPagination.min.js:10 Uncaught Error: Start page option is incorrect
    at new r (jquery.twbsPagination.min.js:10:233)
    at o.fn.twbsPagination (jquery.twbsPagination.min.js:10:5530)
    at HTMLDocument.<anonymous> (list:57:25)
    at j (jquery.js:3148:30)
    at Object.fireWith [as resolveWith] (jquery.js:3260:7)
    at Function.ready (jquery.js:3472:13)
    at HTMLDocument.J (jquery.js:3503:10)
```

2023-03-29 18:48 UTC, agoyal61 commented
Added the condition for total page to handle pagination error

2023-05-10 15:38 UTC, jdamerow commented
Make it so, Jenkins.

2023-05-10 15:41 UTC, merged