Story/cite 172 - From the managed authority page, there should be a link that lists all citations that reference that authority
diging/citesphere pull request #272
Opened 2024-06-18 22:06 UTC by PradnyaC11

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
 

... Put ticket description here and add link to ticket ...

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2024-06-26 16:40 UTC, jdamerow commented
top part of PR is not completely filled out.

2024-09-06 18:39 UTC, jdamerow commented on citesphere/pom.xml
> +        <citesphere.model.version>1.22-SNAPSHOT</citesphere.model.version>
That's not a real version number.

2024-09-06 18:43 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityItemsController.java
> +        userEntries = authorityService.findByUri((IUser) authentication.getPrincipal(), uri);
why is this variable called `userEntries`? It's not users that are held in this list.

2024-09-06 18:43 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityItemsController.java
> +            logger.error("No entry found for URI: " + uri);
that would just mean there are no authority with the uri, it's not an exception in the system really. so no need to log as error, maybe info.

2024-09-06 18:51 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/authority/impl/AuthorityItemsService.java
> +public class AuthorityItemsService implements IAuthorityItemsService {
Is there a reason this is not part of the citation manager class? Also, tests are missing.

2024-10-25 21:23 UTC, jdamerow commented
Resolve conflicts please

2024-11-26 18:52 UTC, jdamerow requested changes

2024-11-26 18:52 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityItemsController.java
> +    private List<IAuthorityEntry> authorityEntries = new ArrayList();
This class is a singleton, so using a global variable like this is a big no no (all request will have the same variable/share the same data).

2024-11-26 18:52 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityItemsController.java
> +            logger.info("No entry found for URI: " + uri);
remove, this is not really useful here.

2024-11-26 18:52 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/authorities/AuthorityItemsController.java
> +            Citations citations = citationManager.findAuthorityItems(authorityEntries.get(0));
this seems to be missing the logged in person (only citations the user has access to should be shown).

2025-01-09 14:32 UTC, jdamerow requested changes

2025-01-09 14:32 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +                    .collect(Collectors.toList());
this filtering should happen on the db level (when calling `findCitationsByPersonUri`)

2025-01-09 14:32 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +    public Citations findAuthorityItems(IAuthorityEntry entry, IUser user) {
that's a confusing name. Why "items"? and it's not finding "authority items", it's finding citations that refer to the given authority, doesn't it?

2025-01-09 14:32 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +    public Citations findAuthorityItems(IAuthorityEntry entry, IUser user) {
also needs tests

2025-01-21 17:58 UTC, jdamerow commented
Make it so, Jenkins.

2025-01-21 22:53 UTC, PradnyaC11 commented
All the tests are passing locally.

2025-02-12 14:38 UTC, jdamerow requested changes

2025-02-12 14:38 UTC, jdamerow commented on citesphere/pom.xml
> +        <citesphere.model.version>1.23</citesphere.model.version>
I believe this needs to be v1.24 to make the compilation errors go away?

2025-02-25 16:15 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-19 14:56 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-19 15:01 UTC, jdamerow commented
The list page needs a heading:
![image](https://github.com/user-attachments/assets/57ecd781-0e55-4361-8030-af389d687292)

Also, when I click on the reference, I get a 400 bad request error

2025-03-19 15:01 UTC, jdamerow commented
And the page also needs a back button.

2025-03-27 16:40 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-27 16:44 UTC, jdamerow commented
- Page needs to show the name of the authority I'm looking at.
- table should use up the whole width
- if there are no citations, then it should say "This authority is not used for any citations."
![image](https://github.com/user-attachments/assets/581354c9-ae19-49a3-afef-408fd029f35e)

2025-04-25 16:26 UTC, jdamerow commented
Make it so, Jenkins.

2025-04-25 16:38 UTC, merged