Bug/cite 221
diging/citesphere pull request #276
Opened 2024-07-16 23:39 UTC by PradnyaC11

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
unique: [Spring Data: Unique field in MongoDB document](https://stackoverflow.com/questions/49385130/spring-data-unique-field-in-mongodb-document)

... Put ticket description here and add link to ticket ...
https://diging.atlassian.net/browse/CITE-221

## Are there any other pull requests that this one depends on?
https://github.com/diging/citesphere-model/pull/51
  
## Anything else the reviewer needs to know?

... describe here ...

2024-07-17 15:17 UTC, jdamerow requested changes
I haven't run this but that does not look right. If there is a duplicate key, then the duplicates should be deleted, so that only one group/citation/collection is left. The user should not get an error, instead the issue should be resolved.

2024-07-17 15:17 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/GroupManager.java
> +            if (!group.getUsers().contains(user.getUsername())) {
if the user does not have access to the group, then they shouldn't be added.

2024-09-10 21:17 UTC, jdamerow reviewed
A new model version has been published but it doesn't look like pom.xml is being changed?

2024-10-25 21:24 UTC, jdamerow commented
Resolve conflicts please

2024-10-29 15:58 UTC, jdamerow requested changes

2024-10-29 15:58 UTC, jdamerow commented on citesphere/pom.xml
> +        <citesphere.model.version>1.23-SNAPSHOT</citesphere.model.version>
this needs to be a proper version

2024-10-29 15:58 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +        if (!groupOptional.isPresent()) {
hm, I'm fairly certain this create a security issue here. Basically, doesn't this say "if the group does not yet locally exist, get it from zotero" (that's fine zotero will complain if the user does not have access), however, "if the group does exist, let's just add the user to the group" (this seems wrong, where is the check if the user has access?).

2024-10-29 15:58 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +            ICitationGroup zeteroGroup = null;
spelling mistake

2024-10-29 19:51 UTC, jdamerow requested changes

2024-10-29 19:51 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/impl/CitationManager.java
> +            }
this should not be needed, should it? this else should only be called if the group is present and the user has access to it?

2024-11-13 19:29 UTC, jdamerow commented
Make it so, Jenkins.

2024-11-13 19:30 UTC, jdamerow commented
There are test failures

2024-11-13 19:31 UTC, jdamerow commented
```
test_addCitationToReferences_nullReferences(edu.asu.diging.citesphere.core.service.impl.CitationManagerTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NullPointerException
```

2024-11-13 19:31 UTC, jdamerow commented
```
test_addCitationToReferences_citationFound(edu.asu.diging.citesphere.core.service.impl.CitationManagerTest)
```

2025-02-12 14:40 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-12 14:44 UTC, jdamerow commented
There are compilation errors
```
CitationManagerTest.java:[483,27] error: cannot find symbol
[ERROR]   symbol:   class ObjectId
```

2025-02-14 22:24 UTC, PradnyaC11 commented
I am not getting the above compilation error on local.

2025-02-21 23:05 UTC, PradnyaC11 commented
Make it so, Jenkins.

2025-02-25 16:51 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-25 17:14 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-25 18:50 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-27 21:59 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-27 22:02 UTC, jdamerow commented
Now it's not deploying:
```
Caused by: com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'Index build failed: f9dbe9da-f364-40e7-b201-e9597d59ab19: Collection citesphere.citation ( 91f861c3-75cc-4b35-87a3-7416b2298590 ) :: caused by :: E11000 duplicate key error collection: citesphere.citation index: key_1 dup key: { key: "4KHE5SI6" }'
	at com.mongodb.internal.operation.CreateIndexesOperation.checkForDuplicateKeyError(CreateIndexesOperation.java:338) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.CreateIndexesOperation.access$300(CreateIndexesOperation.java:72) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:200) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:192) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withConnectionSource(OperationHelper.java:649) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withConnection(OperationHelper.java:611) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:192) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:72) ~[mongodb-driver-core-4.1.0.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:195) ~[mongodb-driver-sync-4.1.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847) ~[mongodb-driver-sync-4.1.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830) ~[mongodb-driver-sync-4.1.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825) ~[mongodb-driver-sync-4.1.2.jar:?]
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810) ~[mongodb-driver-sync-4.1.2.jar:?]
	at org.springframework.data.mongodb.core.DefaultIndexOperations.lambda$ensureIndex$0(DefaultIndexOperations.java:131) ~[spring-data-mongodb-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:566) ~[spring-data-mongodb-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.data.mongodb.core.MongoTemplate.execute(MongoTemplate.java:552) ~[spring-data-mongodb-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.data.mongodb.core.DefaultIndexOperations.execute(DefaultIndexOperations.java:211) ~[spring-data-mongodb-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.data.mongodb.core.DefaultIndexOperations.ensureIndex(DefaultIndexOperations.java:121) ~[spring-data-mongodb-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at edu.asu.diging.citesphere.config.core.MongoConfig$MongoIndex.afterPropertiesSet(MongoConfig.java:120) ~[classes/:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
	... 55 more
```

2025-02-28 23:24 UTC, PradnyaC11 commented
Queries to delete deplicate keys in MongoDB - 
1. For Citation Group --
db.citationGroup.aggregate([
  {
    $group: {
      _id: { key: "$groupId" },  
      latestId: { $max: "$_id" },  
      duplicates: { $push: "$_id" } 
    }
  },
  {
    $project: {
      _id: 1,
      latestId: 1,
      duplicates: {
        $filter: {
          input: "$duplicates",
          as: "dup",
          cond: { $ne: ["$$dup", "$latestId"] } 
        }
      }
    }
  }
]).forEach(doc => {
  db.citationGroup.deleteMany({ _id: { $in: doc.duplicates } });
});

2. For Citation --
db.citation.aggregate([
  {
    $group: {
      _id: { key: "$key" },  
      latestId: { $max: "$_id" },  
      duplicates: { $push: "$_id" } 
    }
  },
  {
    $project: {
      _id: 1,
      latestId: 1,
      duplicates: {
        $filter: {
          input: "$duplicates",
          as: "dup",
          cond: { $ne: ["$$dup", "$latestId"] } 
        }
      }
    }
  }
]).forEach(doc => {
  db.citation.deleteMany({ _id: { $in: doc.duplicates } });
});

3. For Citation Collection
db.citationCollection.aggregate([
  {
    $group: {
      _id: { key: "$key" },  
      latestId: { $max: "$_id" },  
      duplicates: { $push: "$_id" } 
    }
  },
  {
    $project: {
      _id: 1,
      latestId: 1,
      duplicates: {
        $filter: {
          input: "$duplicates",
          as: "dup",
          cond: { $ne: ["$$dup", "$latestId"] } 
        }
      }
    }
  }
]).forEach(doc => {
  db.citationCollection.deleteMany({ _id: { $in: doc.duplicates } });
});

2025-03-03 19:24 UTC, jdamerow commented
In the future, please mark up code in markdown so it is treated as code (` ```code``` `).

2025-03-03 19:24 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-03 19:31 UTC, merged