Story/cite 223 - DOI field should be shown on citation pages
diging/citesphere pull request #277
Opened 2024-07-29 17:41 UTC by PradnyaC11

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 

... Put ticket description here and add link to ticket ...
DOI field should be shown on citation pages

https://diging.atlassian.net/browse/CITE-223

## Are there any other pull requests that this one depends on?
https://github.com/diging/citesphere-model/pull/53
https://github.com/diging/spring-social-zotero/pull/23
  
## Anything else the reviewer needs to know?

... describe here ...

2024-09-13 20:14 UTC, jdamerow requested changes

2024-09-13 20:14 UTC, jdamerow commented on citesphere/pom.xml
> +        <citesphere.model.version>1.22-SNAPSHOT</citesphere.model.version>
versions don't exist

2024-09-26 20:29 UTC, jdamerow commented
Make it so, Jenkins.

2024-09-26 20:40 UTC, jdamerow commented
DOI (probably also ISSN) is not showing up; also, those fields are not shown when editing.

2024-11-26 18:10 UTC, jdamerow commented
Make it so, Jenkins.

2024-12-05 18:49 UTC, PradnyaC11 commented
This is working for me on local. It's dependent on - https://github.com/diging/spring-social-zotero/pull/23. Maybe after that PR is merged, this will work in review.

2025-01-09 14:38 UTC, jdamerow reviewed
`spring-social-zotero` needs to be updated I presume?

2025-02-12 14:46 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-12 14:52 UTC, jdamerow commented
Now it looks like while I do get DOI and ISSN, after I changed the citation and saved it in Citesphere, the DOI got deleted.

2025-02-27 22:03 UTC, jdamerow commented
Make it so, Jenkins.

2025-02-27 22:11 UTC, merged