Story/cite 174 - There should be an API endpoint to create new items
diging/citesphere pull request #280
Opened 2024-09-12 18:42 UTC by PradnyaC11

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
There should be an API endpoint to create new items

... Put ticket description here and add link to ticket ...
It should be possible to also send files in requests that will start a giles upload.
This will probably need a full Giles setup. Talk to Julia first before picking this ticket.

https://diging.atlassian.net/browse/CITE-174

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2024-09-12 18:58 UTC, jdamerow commented
Make it so, Jenkins.

2024-09-12 19:38 UTC, jdamerow requested changes
If there is no item type provided, there should be an appropriate error response (right now it throws an exception). And please document it in Confluence and put the link here before reopening.

2024-09-13 17:23 UTC, PradnyaC11 commented
Confluence updated with this endpoint - https://diging.atlassian.net/wiki/spaces/CITED/pages/2080899073/API+Documentation#Create-Item-Endpoint

2024-09-13 19:01 UTC, jdamerow requested changes

2024-09-13 19:01 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +            return new ResponseEntity<>("Error: Missing Item Type", HttpStatus.INTERNAL_SERVER_ERROR);
that should be a bad request response

2024-09-13 19:01 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +                } catch (Exception e) {
this should be the proper exception types, not just a catch all.

2024-09-13 19:04 UTC, jdamerow commented
For the documentation, what about all the other files (creators, dates, etc) how are these submittted?

2024-09-13 20:53 UTC, jdamerow requested changes

2024-09-13 20:53 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +                    return new ResponseEntity<>("Error: Could not find the newly created citation.", HttpStatus.BAD_REQUEST);
I think in this case, we want to return a 500. Afterall, there is nothing the user could do here, it would indicate some internal issue.

2024-09-17 15:32 UTC, jdamerow requested changes

2024-09-17 15:32 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +            return new ResponseEntity<>("Error: Zetero Item creation failed. " + e.getLocalizedMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
exception needs to be logged

2024-09-17 15:32 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/util/IGilesUtil.java
> +public interface IGilesUtil {
javadoc missing

2024-09-17 15:32 UTC, jdamerow commented
Make it so, Jenkins.

2024-09-17 15:40 UTC, jdamerow commented
Documentation:
- needs to explain what the different error codes mean
- needs to link to a list of itemTypes

Code:
- when the item type is not valid, I just get a bad request back (no explanation what's wrong)
- if I submit author or otherCreator (presumably also editor), I just get a bad request back (no explanation what's wrong). my guess is the value needs to be of a certain format but I don't know what that is.

2024-09-17 15:40 UTC, jdamerow commented
File submission works though!

2024-09-24 17:53 UTC, jdamerow requested changes

2024-09-26 20:04 UTC, jdamerow requested changes

2024-09-26 20:27 UTC, jdamerow commented
I cannot get the create item with authors/editors/contributors to work. The server throws
```
[ERROR] 2024-09-26 20:21:56.067 [http-nio-8080-exec-156] AddNewItemController - Could not parse otherCreators
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList` out of START_OBJECT token
 at [Source: (String)"[{
  "id": null,
  "firstName": "Tim",
  "lastName": "Berners-Lee",
  "position": 1,
  "role": "author",
  "affiliations": { "name": "ASU"}
}]"; line: 7, column: 19] (through reference chain: java.util.ArrayList[0]->edu.asu.diging.citesphere.web.forms.PersonForm["affiliations"])
```
Also a couple of notes for the document:
- shouldn't the authors/editors/otherCreators lists should get a list (so `[...]` not just one json object? If so, that needs to be documented.
-  there is not point to have id, or role for authors (there is no id, role is always "author") and same for editors (editors will always have the role "editor"). for otherCreators role makes sense.
- affiliations also won't have an id field

2024-09-26 20:44 UTC, jdamerow commented
Make it so, Jenkins.

2024-09-26 20:45 UTC, jdamerow commented
Make it so, Jenkins.

2024-10-02 18:24 UTC, PradnyaC11 commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +                    logger.error("Could not parse authors", e);
These exceptions are not getting handled anywhere else. This InitBinder is called while mapping the body parameters to the object attributes, hence they are logged here.

2024-10-22 01:04 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/api/v1/user/AddNewItemController.java
> +            for (int i=0; i<itemWithGiles.getFiles().length; i++) {
foreach loops are easier to read and therefore maintain and also use an iterator under the hood, which can be advantages in certain situations.

2024-10-22 15:37 UTC, jdamerow commented
Make it so, Jenkins.

2024-10-22 15:45 UTC, merged