Story/cite 235 - It needs to be possible to check on an upload in Giles by hand.
diging/citesphere pull request #291
Opened 2024-12-18 23:09 UTC by PradnyaC11

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [ ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ ] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [ ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ ] I am not reformatting any files in the wrong format or without cause. 
- [ ] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
It needs to be possible to check on an upload in Giles by hand.

... Put ticket description here and add link to ticket ...
Currently if something goes wrong during an upload or Citesphere restarts, a file submitted to Giles will just keep having the status in progress. There should be a little icon next to files that initiates a check on the status of a file by hand.

https://diging.atlassian.net/browse/CITE-235

## Are there any other pull requests that this one depends on?

  
## Anything else the reviewer needs to know?

... describe here ...

2025-02-12 15:05 UTC, jdamerow commented
Hm, no, I think this should be a synchronous check, not adding an upload to the check queue (that although maybe too). when the user clicks the sync icon, a request to giles about the status should be made and if the files is still being processed, then the upload should be added to the check queue. if it's done or failed, the upload status should be updated to reflect that. does that make sense?

2025-03-27 17:36 UTC, jdamerow commented
Make it so, Jenkins.

2025-03-27 17:49 UTC, jdamerow commented
Got a null pointer trying to sync: https://diging-dev.asu.edu/citesphere-review/auth/group/2256709/items/Z29BR7XB?index=20&page=1&sortBy=title (and multiple others)

```
java.lang.NullPointerException
	edu.asu.diging.citesphere.core.service.impl.GroupManager.getGroup(GroupManager.java:43)
	edu.asu.diging.citesphere.core.service.impl.CitationManager.getCitation(CitationManager.java:118)
	edu.asu.diging.citesphere.core.service.impl.CitationManager$$FastClassBySpringCGLIB$$275ff5c1.invoke(<generated>)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	edu.asu.diging.citesphere.core.service.impl.CitationManager$$EnhancerBySpringCGLIB$$c20abc93.getCitation(<generated>)
	edu.asu.diging.citesphere.core.service.giles.impl.GilesUploadCheckerImpl.getCurrentCitation(GilesUploadCheckerImpl.java:215)
	edu.asu.diging.citesphere.core.service.giles.impl.GilesUploadCheckerImpl.checkUploadStatus(GilesUploadCheckerImpl.java:172)
	edu.asu.diging.citesphere.web.user.SyncItemController.getGilesstatus(SyncItemController.java:42)
```

2025-04-25 21:26 UTC, jdamerow requested changes

2025-04-25 21:26 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +    public void checkUploadStatus(String citationKey, IUser user) {
needs javadoc

2025-04-25 21:26 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/SyncItemController.java
> +    public String getGilesstatus(Authentication authentication, Model model, @PathVariable("zoteroGroupId") String zoteroGroupId,
this should be in its own controller. it's its own use case.

2025-04-25 21:26 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/web/user/SyncItemController.java
> +        uploadChecker.checkUploadStatus(itemId, (IUser)authentication.getPrincipal());
I actually don't think we want to check this here. Make it two different actions: update the item data from zotoro and check on the upload status of the giles upload.

2025-04-25 21:26 UTC, jdamerow commented
Make it so, Jenkins.

2025-04-25 21:31 UTC, jdamerow commented
And actually, the way it is implemented right now it suggests that the status is just check for one file (the one for which one would click the refresh icon), but it actually checks all of them, doesn't it?

2025-05-06 20:20 UTC, jdamerow requested changes

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        int unfinishedUplaods = currentCitation.getGilesUploads().stream()
so if currentCitation is null in line 134, then this would throw a null pointer, wouldn't it?

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        if(user == null) {
in what case would this be true? and should Citesphere then simply use the uploaded users token (instead of the token of the user that is checking the status)?

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        if(user == null) {
in other words, if this is a valid scenario there needs to be some explanation here.

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        }
let's put the code that makes the actual call to giles into its own method

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +            GilesUpload[] processed = new GilesUpload[0];
is there a reason `processed` is initialized here? For what? either `readValue` will return a GilesUpload array, or the method will return.

2025-05-06 20:20 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +    public void checkFileUploadStatus(String citationKey, IUser user, String processId) {
javadoc

2025-05-06 20:20 UTC, jdamerow commented
Make it so, Jenkins.

2025-05-06 20:28 UTC, jdamerow commented
Might be the issue I pointed out in my comments (this is when I click on the icon for a failed upload):
```
java.lang.NullPointerException
	java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	edu.asu.diging.citesphere.core.service.giles.impl.GilesUploadCheckerImpl.checkFileUploadStatus(GilesUploadCheckerImpl.java:259)
	edu.asu.diging.citesphere.web.user.SyncGilesStatusController.getGilesstatus(SyncGilesStatusController.java:31)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
(also, for a failed upload there should probably be no sync icon. or for successfully proceed uploads.)

2025-05-06 23:25 UTC, PradnyaC11 commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        }
This method was made for giles call, with minimum extra code.

2025-05-07 14:08 UTC, jdamerow commented on citesphere/src/main/java/edu/asu/diging/citesphere/core/service/giles/impl/GilesUploadCheckerImpl.java
> +        }
I mean this part:
```
        String token = internalTokenManager.getAccessToken(user).getValue();

        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(token);
        HttpEntity<MultiValueMap<String, Object>> requestEntity = new HttpEntity<>(
                headers);

        ResponseEntity<String> response;
        return restTemplate.exchange(
                    gilesBaseurl + gilesCheckEndpoint + upload.getProgressId(),
                    HttpMethod.GET, requestEntity, String.class);
```
Separate the different responsibilities:
- making a call to the API
- handling what comes back

2025-05-30 21:02 UTC, jdamerow commented
Make it so, Jenkins.

2025-06-13 16:40 UTC, jdamerow commented
Make it so, Jenkins.

2025-06-13 16:57 UTC, merged